#!/usr/bin/env bash

function Indent() {
  sed -e 's/^/  /'
}

use_shell=0 # Let's use nix-build rather than nix-shell (and cabal commands).

if [[ $use_shell == 1 ]]; then
  echo "Good examples"
  cabal2nix --shell . |
    nix-shell --command 'cabal v2-run huttons-razor -- "1 + 2" "3 + 4"' - |
    Indent

  echo
  echo "Bad examples"
  cabal2nix --shell . |
    nix-shell --command 'cabal v2-run huttons-razor -- "" "+" "1+" "1 - 2"' |
    Indent
else
  echo "Good examples"
  ./result/bin/huttons-razor "1 + 2" "3 + 4" | Indent

  echo
  echo "Bad examples"
  ./result/bin/huttons-razor "" "+" "1+" "1 - 2" | Indent
fi
